// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goreleases.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	goreleases.proto

It has these top-level messages:
	GetReleaseInfoRequest
	ListReleasesRequest
	ListReleasesResponse
	ReleaseInfo
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GetReleaseInfoRequest struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *GetReleaseInfoRequest) Reset()                    { *m = GetReleaseInfoRequest{} }
func (m *GetReleaseInfoRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetReleaseInfoRequest) ProtoMessage()               {}
func (*GetReleaseInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetReleaseInfoRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ListReleasesRequest struct {
}

func (m *ListReleasesRequest) Reset()                    { *m = ListReleasesRequest{} }
func (m *ListReleasesRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListReleasesRequest) ProtoMessage()               {}
func (*ListReleasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListReleasesResponse struct {
	Releases []*ReleaseInfo `protobuf:"bytes,1,rep,name=releases" json:"releases,omitempty"`
}

func (m *ListReleasesResponse) Reset()                    { *m = ListReleasesResponse{} }
func (m *ListReleasesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListReleasesResponse) ProtoMessage()               {}
func (*ListReleasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListReleasesResponse) GetReleases() []*ReleaseInfo {
	if m != nil {
		return m.Releases
	}
	return nil
}

type ReleaseInfo struct {
	Version         string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	ReleaseDate     string `protobuf:"bytes,2,opt,name=releaseDate" json:"releaseDate,omitempty"`
	ReleaseNotesURL string `protobuf:"bytes,3,opt,name=releaseNotesURL" json:"releaseNotesURL,omitempty"`
}

func (m *ReleaseInfo) Reset()                    { *m = ReleaseInfo{} }
func (m *ReleaseInfo) String() string            { return proto1.CompactTextString(m) }
func (*ReleaseInfo) ProtoMessage()               {}
func (*ReleaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReleaseInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ReleaseInfo) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *ReleaseInfo) GetReleaseNotesURL() string {
	if m != nil {
		return m.ReleaseNotesURL
	}
	return ""
}

func init() {
	proto1.RegisterType((*GetReleaseInfoRequest)(nil), "proto.GetReleaseInfoRequest")
	proto1.RegisterType((*ListReleasesRequest)(nil), "proto.ListReleasesRequest")
	proto1.RegisterType((*ListReleasesResponse)(nil), "proto.ListReleasesResponse")
	proto1.RegisterType((*ReleaseInfo)(nil), "proto.ReleaseInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoReleaseService service

type GoReleaseServiceClient interface {
	GetReleaseInfo(ctx context.Context, in *GetReleaseInfoRequest, opts ...grpc.CallOption) (*ReleaseInfo, error)
	ListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*ListReleasesResponse, error)
}

type goReleaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoReleaseServiceClient(cc *grpc.ClientConn) GoReleaseServiceClient {
	return &goReleaseServiceClient{cc}
}

func (c *goReleaseServiceClient) GetReleaseInfo(ctx context.Context, in *GetReleaseInfoRequest, opts ...grpc.CallOption) (*ReleaseInfo, error) {
	out := new(ReleaseInfo)
	err := grpc.Invoke(ctx, "/proto.GoReleaseService/GetReleaseInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goReleaseServiceClient) ListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*ListReleasesResponse, error) {
	out := new(ListReleasesResponse)
	err := grpc.Invoke(ctx, "/proto.GoReleaseService/ListReleases", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoReleaseService service

type GoReleaseServiceServer interface {
	GetReleaseInfo(context.Context, *GetReleaseInfoRequest) (*ReleaseInfo, error)
	ListReleases(context.Context, *ListReleasesRequest) (*ListReleasesResponse, error)
}

func RegisterGoReleaseServiceServer(s *grpc.Server, srv GoReleaseServiceServer) {
	s.RegisterService(&_GoReleaseService_serviceDesc, srv)
}

func _GoReleaseService_GetReleaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoReleaseServiceServer).GetReleaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GoReleaseService/GetReleaseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoReleaseServiceServer).GetReleaseInfo(ctx, req.(*GetReleaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoReleaseService_ListReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoReleaseServiceServer).ListReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GoReleaseService/ListReleases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoReleaseServiceServer).ListReleases(ctx, req.(*ListReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoReleaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GoReleaseService",
	HandlerType: (*GoReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReleaseInfo",
			Handler:    _GoReleaseService_GetReleaseInfo_Handler,
		},
		{
			MethodName: "ListReleases",
			Handler:    _GoReleaseService_ListReleases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goreleases.proto",
}

func init() { proto1.RegisterFile("goreleases.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xdb, 0x4a, 0x03, 0x31,
	0x10, 0x6d, 0x2c, 0xde, 0x66, 0x45, 0xcb, 0x68, 0x21, 0xac, 0x3e, 0x2c, 0x79, 0xda, 0xa7, 0x05,
	0xeb, 0x2f, 0x14, 0x4b, 0xa1, 0xf8, 0x10, 0xf1, 0x03, 0xaa, 0x8c, 0xb2, 0x20, 0x3b, 0x35, 0x13,
	0xfb, 0x43, 0xfe, 0xa8, 0x90, 0xcd, 0x4a, 0x56, 0xd2, 0xa7, 0x30, 0xe7, 0xc2, 0x39, 0x39, 0x30,
	0xfb, 0x60, 0x47, 0x9f, 0xb4, 0x15, 0x92, 0x66, 0xe7, 0xd8, 0x33, 0x1e, 0x87, 0xc7, 0xdc, 0xc3,
	0x7c, 0x45, 0xde, 0xf6, 0xdc, 0xba, 0x7b, 0x67, 0x4b, 0x5f, 0xdf, 0x24, 0x1e, 0x35, 0x9c, 0xee,
	0xc9, 0x49, 0xcb, 0x9d, 0x56, 0x95, 0xaa, 0xcf, 0xed, 0x70, 0x9a, 0x39, 0x5c, 0x6f, 0x5a, 0x19,
	0x3c, 0x12, 0x0d, 0xe6, 0x11, 0x6e, 0xc6, 0xb0, 0xec, 0xb8, 0x13, 0xc2, 0x06, 0xce, 0x86, 0x68,
	0xad, 0xaa, 0x69, 0x5d, 0x2c, 0xb0, 0xaf, 0xd0, 0xa4, 0xa9, 0x7f, 0x1a, 0x23, 0x50, 0x24, 0xc4,
	0xe1, 0x1e, 0x58, 0x41, 0x11, 0x4d, 0xcb, 0xad, 0x27, 0x7d, 0x14, 0xd8, 0x14, 0xc2, 0x1a, 0xae,
	0xe2, 0xf9, 0xc4, 0x9e, 0xe4, 0xc5, 0x6e, 0xf4, 0x34, 0xa8, 0xfe, 0xc3, 0x8b, 0x1f, 0x05, 0xb3,
	0x15, 0xc7, 0xdc, 0x67, 0x72, 0xfb, 0xf6, 0x8d, 0x70, 0x09, 0x97, 0xe3, 0x6d, 0xf0, 0x2e, 0x36,
	0xcf, 0x4e, 0x56, 0x66, 0xfe, 0x65, 0x26, 0xb8, 0x86, 0x8b, 0x74, 0x17, 0x2c, 0xa3, 0x2a, 0xb3,
	0x61, 0x79, 0x9b, 0xe5, 0xfa, 0x21, 0xcd, 0xe4, 0xf5, 0x24, 0xb0, 0x0f, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x94, 0x08, 0xae, 0x6d, 0xce, 0x01, 0x00, 0x00,
}
